apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-manager
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-manager
  template:
    metadata:
      labels:
        app: kafka-manager
    spec:
      containers:
      - name: kafka-manager
        image: solsson/kafka-manager@sha256:9da595ecbb733074a1d3c6091a1e0c384da4f4e1f19f4e16276062278da8e592
        ports:
        - containerPort: 80
        env:
        - name: ZK_HOSTS
          value: zookeeper.kafka:2181
        - name: KAFKA_MANAGER_USERNAME
          value: admin
        - name: KAFKA_MANAGER_PASSWORD
          value: adminSEF
        command:
        - ./bin/kafka-manager
        - -Dhttp.port=80
        volumeMounts:
        - name: basic-authentication
          mountPath: /opt/kafka-manager/conf/application.conf
          subPath: application.conf
      volumes:
        - name: basic-authentication
          configMap:
            name: manager-config
